# Generated by Django 3.2.9 on 2022-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whether_version', models.IntegerField(choices=[(0, '版本'), (1, '活动'), (2, '其它')], default=0, verbose_name='是否版本')),
                ('version', models.CharField(default='未知', max_length=50, verbose_name='版本名称')),
                ('url_name', models.CharField(default='未知接口名称', max_length=50, verbose_name='接口名称')),
                ('domain_or_ipaddress', models.CharField(default='http://123.57.42.55', max_length=100, null=True, verbose_name='域名或IP地址')),
                ('port', models.IntegerField(choices=[(20100, '20100'), (20010, '20010'), (20020, '20020'), (20800, '20800'), (8080, '8080'), (0, '无')], default=0, verbose_name='端口')),
                ('url', models.CharField(default='', max_length=512, verbose_name='请求地址(url)')),
                ('headers', models.TextField(blank=True, default='', null=True, verbose_name='headers请求头')),
                ('method', models.CharField(choices=[('post', 'POST'), ('get', 'GET')], default='post', max_length=10, verbose_name='请求方法')),
                ('pre_case_id', models.IntegerField(default=0, verbose_name='前置用例(id)')),
                ('pre_fields', models.TextField(blank=True, default='[]', max_length=512, null=True, verbose_name='前置字段')),
                ('case_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='用例编号')),
                ('parameter_interpretation', models.TextField(blank=True, max_length=512, null=True, verbose_name='参数释意')),
                ('variable_parameters', models.TextField(blank=True, max_length=512, null=True, verbose_name='变动参数')),
                ('request_parameters', models.TextField(default='', verbose_name='请求参数')),
                ('interface_status', models.IntegerField(choices=[(0, '正常'), (1, '已关闭'), (2, '已废弃'), (3, '预留')], default=0, verbose_name='接口状态')),
                ('run', models.CharField(choices=[('yes', '是'), ('no', '否')], default='yes', max_length=4, verbose_name='是否运行')),
                ('assert_type', models.IntegerField(choices=[(0, '无'), (1, 'options'), (2, 'options_item'), (3, 'options_list'), (4, 'options_item_list')], default=0, verbose_name='断言类型')),
                ('expect_result', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='预期结果')),
                ('response', models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='响应数据')),
                ('pass_or_not', models.IntegerField(blank=True, choices=[(0, '未知'), (1, '通过'), (2, '不通过')], default=0, null=True, verbose_name='测试结果')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
            },
        ),
    ]
