# Generated by Django 3.2.9 on 2022-03-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assert_type',
            field=models.IntegerField(choices=[(0, '无'), (1, 'options'), (2, 'options_item'), (3, 'options_list'), (4, 'options_item_list')], default=0, verbose_name='断言类型'),
        ),
        migrations.AlterField(
            model_name='case',
            name='port',
            field=models.IntegerField(choices=[(20100, '20100'), (20010, '20010'), (20020, '20020'), (20800, '20800'), (8080, '8080'), (0, '无')], default=0, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pre_fields',
            field=models.TextField(blank=True, default='[]', max_length=512, null=True, verbose_name='前置字段'),
        ),
    ]
